# tasks
---
- name: Console TTY1
  include: pi-console-tty1.yml
  when: pi_console_tty1 is defined
      
- name: Console TTY3
  include: pi-console-tty3.yml
  when: pi_console_tty3 is defined

      
- name: GPU Memory Reset
  include: pi-gpumem-reset.yml
  when: pi_gpumem_reset is defined

- name: Set GPU Memory --> 128MB
  include: pi-gpumem-128mb.yml
  when: pi_gpumem_128mb is defined


# Node.js 
- name: "Node.js Current Variables"
  include_vars: pi-nodejs-current.yml
  when: pi_nodejs_current is defined
- name: "Node.js Current"
  include: pi-nodejs-current.yml
  when: pi_nodejs_current is defined

- name: "Node.js LTS Variables"
  include_vars: pi-nodejs-lts.yml
  when: pi_nodejs_lts is defined
- name: "Node.js LTS"
  include: pi-nodejs-lts.yml
  when: pi_nodejs_lts is defined

- include: pi-nologo.yml
  when: pi_nologo is defined


- include: pi-usb-maxcurrent-reset.yml
  when: pi_usb_maxcurrent_reset is defined

- include: pi-usb-maxcurrent.yml
  when: pi_usb_maxcurrent is defined

...

