# tasks
---

# debug
- debug: msg="ansible_distribution {{ansible_distribution}}"
- debug: msg="ansible_distribution_release {{ansible_distribution_release}}"
- debug: msg="ansible_distribution_release {{ansible_distribution_version}}"

# /boot/cmdline.txt
- name: "pi-console-tty1"
  include: pi-console-tty1.yml
  when: pi_console_tty1 is defined
      
- name: "pi-console-tty3"
  include: pi-console-tty3.yml
  when: pi_console_tty3 is defined

- name: "pi-nologo"
  include: pi-nologo.yml
  when: pi_nologo is defined

- name: "pi-quiet"
  include: pi-quiet.yml
  when: pi_quiet is defined
      
- name: "pi-gpumem-reset" 
  include: pi-gpumem-reset.yml
  when: pi_gpumem_reset is defined

- name: "pi-gpumem-128mb"
  include: pi-gpumem-128mb.yml
  when: pi_gpumem_128mb is defined

- name: "pi-cursor-off"
  include: pi-cursor-off.yml
  when: pi_cursor_off is defined

- name: "pi-loglevel-2"
  include: pi-loglevel-2.yml
  when: pi_loglevel_2 is defined

      
# /boot/config.txt
- name: "pi-usb-maxcurrent-reset"
  include: pi-usb-maxcurrent-reset.yml
  when: pi_usb_maxcurrent_reset is defined

- name: "pi-usb-maxcurrent"
  include: pi-usb-maxcurrent.yml
  when: pi_usb_maxcurrent is defined


# System Config
- name: "pi-locale"
  include: pi-locale.yml
  when: pi_locale is defined

- name: "pi-getty-tty-off"
  include: pi-getty-tty-off.yml
  when: pi_getty_tty_off is defined
      
- name: "pi-local-ssh-key"
  include: pi-local-ssh-key.yml
  when: pi-local-ssh-key is defined

# Software 
- name: "pi-nodejs-current Variables"
  include_vars: pi-nodejs-current.yml
  when: pi_nodejs_current is defined
- name: "pi-nodejs-current"
  include: pi-nodejs-current.yml
  when: pi_nodejs_current is defined

- name: "pi-nodejs-lts Variables"
  include_vars: pi-nodejs-lts.yml
  when: pi_nodejs_lts is defined
- name: "pi-nodejs-lts"
  include: pi-nodejs-lts.yml
  when: pi_nodejs_lts is defined



...

