# tasks
---

# debug
- debug: msg="ansible_architecture = {{ansible_architecture}}"
- debug: msg="ansible_distribution = {{ansible_distribution}}"
- debug: msg="ansible_distribution_release = {{ansible_distribution_release}}"
- debug: msg="ansible_distribution_release = {{ansible_distribution_version}}"

# variables


# /boot/cmdline.txt
- name: "pi-console-tty1"
  include: pi-console-tty1.yml
  when: pi_console_tty1 is defined
      
- name: "pi-console-tty3"
  include: pi-console-tty3.yml
  when: pi_console_tty3 is defined

- name: "pi-nologo"
  include: pi-nologo.yml
  when: pi_nologo is defined

- name: "pi-quiet"
  include: pi-quiet.yml
  when: pi_quiet is defined
      
- name: "pi-gpumem-quarter" 
  include: pi-gpumem-quarter.yml
  when: pi_gpumem_quarter is defined

- name: "pi-gpumem-half" 
  include: pi-gpumem-half.yml
  when: pi_gpumem_half is defined

- name: "pi-gpumem-reset" 
  include: pi-gpumem-reset.yml
  when: pi_gpumem_reset is defined

- name: "pi-gpumem"
  include: pi-gpumem.yml
  when: pi_gpumem is defined

- name: "pi-cursor-off"
  include: pi-cursor-off.yml
  when: pi_cursor_off is defined

- name: "pi-loglevel-2"
  include: pi-loglevel-2.yml
  when: pi_loglevel_2 is defined

      
# /boot/config.txt
- name: "pi-usb-maxcurrent-reset"
  include: pi-usb-maxcurrent-reset.yml
  when: pi_usb_maxcurrent_reset is defined

- name: "pi-usb-maxcurrent"
  include: pi-usb-maxcurrent.yml
  when: pi_usb_maxcurrent is defined


# System Config
- name: "pi-local-ssh-key"
  include: pi-local-ssh-key.yml
  when: pi-local-ssh-key is defined
    
- name: "pi-locale"
  include: pi-locale.yml
  when: pi_locale is defined

- name: "pi-timezone"
  include: pi-timezone.yml
  when: pi_timezone is defined

- name: "pi-keyboard"
  include: pi-keyboard.yml
  when: pi_keyboard is defined

- name: "pi-getty-tty-off"
  include: pi-getty-tty-off.yml
  when: pi_getty_tty_off is defined
      

# Software 
- name: "pi-nodejs"
  include: pi-nodejs-current.yml
  when: pi_nodejs is defined

- name: "pi-nodejs-lts"
  include: pi-nodejs-lts.yml
  when: pi_nodejs_lts is defined

- name: "pi-golang"
  include: pi-golang.yml
  when: pi_golang is defined

- name: "pi-omxplayer"
  include: pi-omxplayer.yml
  when: pi_omxplayer is defined   

- name: "pi-install-package"
  include: pi-install-package.yml
  when: pi_install is defined   

...

