---
- name: "Include GPU memory Reset"
  include: pi-gpumem-reset.yml

- name: "Set GPU memory to quarter of system memory"
  become: true
  lineinfile: dest=/boot/config.txt line="{{ item }}" state=present
  with_items:
      - gpu_mem_256=64
      - gpu_mem_512=128
      - gpu_mem_1024=256

...

