---
- name: "Install netpbm Package" 
  become: true
  apt: name=netpbm state=installed update_cache=true cache_valid_time=3600

- name: "Ensure path exists"
  become: true
  file: path=/opt/splash state=directory
      
- name: "Copy Files"
  become: true
  copy: src="{{ item.src }}" dest="{{ item.dest }}" mode="{{ item.mode }}"
  with_items:
      - { src: "splash.png", dest: "/opt/splash/", mode: "u=rw,g=r,o=r" }
      - { src: "splash.sh", dest: "/opt/splash/", mode: "u=rx,g=rx,o=rx" }
      - { src: "showppm", dest: "/opt/splash/", mode: "u=rx,g=rx,o=rx" }
      - { src: "splash.service", dest: "/etc/systemd/system/", mode: "u=rw,g=r,o=r" }

- name: "Generate: splash.ppm"
  become: true
  command: bash -c "pngtopnm /opt/splash/splash.png > /opt/splash/splash.ppm"

- name: "Enable: splash.service"
  become: true
  command: /bin/systemctl enable splash.service


...
