---
- name: "Setup timezone --> {{ pi_timezone_location }}"
  become: true
  copy:
    content: "{{ pi_timezone_location }}"
    dest: /etc/timezone
    mode: 0644


- name: "Update Timezone"
  become: true
  command: dpkg-reconfigure --frontend noninteractive tzdata   
...
